package me.c3.ui.theme.icons

import com.formdev.flatlaf.extras.FlatSVGIcon

class BenIcons : ProSimIcons {
    override val add: FlatSVGIcon = FlatSVGIcon("benicons/add.svg")
    override val autoscroll: FlatSVGIcon = FlatSVGIcon("benicons/autoscroll.svg")
    override val backwards: FlatSVGIcon = FlatSVGIcon("benicons/backwards.svg")
    override val bars: FlatSVGIcon = FlatSVGIcon("benicons/bars.svg")
    override val build: FlatSVGIcon = FlatSVGIcon("benicons/build.svg")
    override val cancel: FlatSVGIcon = FlatSVGIcon("benicons/cancel.svg")
    override val clearStorage: FlatSVGIcon = FlatSVGIcon("benicons/clear_storage.svg")
    override val combineCells: FlatSVGIcon = FlatSVGIcon("benicons/combine_cells.svg")
    override val continuousExe: FlatSVGIcon = FlatSVGIcon("benicons/continuous_exe.svg")
    override val darkmode: FlatSVGIcon = FlatSVGIcon("benicons/darkmode.svg")
    override val deleteBlack: FlatSVGIcon = FlatSVGIcon("benicons/delete_black.svg")
    override val deleteRed: FlatSVGIcon = FlatSVGIcon("benicons/delete_red.svg")
    override val disassembler: FlatSVGIcon = FlatSVGIcon("benicons/disassembler.svg")
    override val edit: FlatSVGIcon = FlatSVGIcon("benicons/edit.svg")
    override val export: FlatSVGIcon = FlatSVGIcon("benicons/export.svg")
    override val fileCompiled: FlatSVGIcon = FlatSVGIcon("benicons/file_compiled.svg")
    override val fileNotCompiled: FlatSVGIcon = FlatSVGIcon("benicons/file_not_compiled.svg")
    override val forwards: FlatSVGIcon = FlatSVGIcon("benicons/forwards.svg")
    override val home: FlatSVGIcon = FlatSVGIcon("benicons/home.svg")
    override val import: FlatSVGIcon = FlatSVGIcon("benicons/import.svg")
    override val info: FlatSVGIcon = FlatSVGIcon("benicons/info.svg")
    override val lightmode: FlatSVGIcon = FlatSVGIcon("benicons/lightmode.svg")
    override val logo: FlatSVGIcon = FlatSVGIcon("benicons/logo.svg")
    override val pin: FlatSVGIcon = FlatSVGIcon("benicons/pin.svg")
    override val processor: FlatSVGIcon = FlatSVGIcon("benicons/processor.svg")
    override val processorBold: FlatSVGIcon = FlatSVGIcon("benicons/processor_bold.svg")
    override val processorLight: FlatSVGIcon = FlatSVGIcon("benicons/processor_light.svg")
    override val recompile: FlatSVGIcon = FlatSVGIcon("benicons/recompile.svg")
    override val refresh: FlatSVGIcon = FlatSVGIcon("benicons/refresh.svg")
    override val reportBug: FlatSVGIcon = FlatSVGIcon("benicons/report_bug.svg")
    override val returnSubroutine: FlatSVGIcon = FlatSVGIcon("benicons/return_subroutine.svg")
    override val reverse: FlatSVGIcon = FlatSVGIcon("benicons/reverse.svg")
    override val settings: FlatSVGIcon = FlatSVGIcon("benicons/settings.svg")
    override val singleExe: FlatSVGIcon = FlatSVGIcon("benicons/single_exe.svg")
    override val splitCells: FlatSVGIcon = FlatSVGIcon("benicons/split_cells.svg")
    override val statusError: FlatSVGIcon = FlatSVGIcon("benicons/status_error.svg")
    override val statusFine: FlatSVGIcon = FlatSVGIcon("benicons/status_fine.svg")
    override val statusLoading: FlatSVGIcon = FlatSVGIcon("benicons/status_loading.svg")
    override val stepInto: FlatSVGIcon = FlatSVGIcon("benicons/step_into.svg")
    override val stepMultiple: FlatSVGIcon = FlatSVGIcon("benicons/step_multiple.svg")
    override val stepOut: FlatSVGIcon = FlatSVGIcon("benicons/step_out.svg")
    override val stepOver: FlatSVGIcon = FlatSVGIcon("benicons/step_over.svg")
    override val tag: FlatSVGIcon = FlatSVGIcon("benicons/tag.svg")
}