package ui

data object Resources {

    data object Icons {
        const val add = "benicons/add.svg"
        const val autoscroll = "benicons/autoscroll.svg"
        const val backwards = "benicons/backwards.svg"
        const val bars = "benicons/bars.svg"
        const val build = "benicons/build.svg"
        const val cancel = "benicons/cancel.svg"
        const val clear_storage = "benicons/clear_storage.svg"
        const val continuous_exe = "benicons/continuous_exe.svg"
        const val darkmode = "benicons/darkmode.svg"
        const val delete_red = "benicons/delete_red.svg"
        const val delete_black = "benicons/delete_black.svg"
        const val disassembler = "benicons/disassembler.svg"
        const val edit = "benicons/edit.svg"
        const val export = "benicons/export.svg"
        const val file_compiled = "benicons/file_compiled.svg"
        const val file_not_compiled = "benicons/file_not_compiled.svg"
        const val forwards = "benicons/forwards.svg"
        const val home = "benicons/home.svg"
        const val import = "benicons/import.svg"
        const val info = "benicons/info.svg"
        const val lightmode = "benicons/lightmode.svg"
        const val logo = "benicons/logo.svg"
        const val pin = "benicons/pin.svg"
        const val processor = "benicons/processor.svg"
        const val processor_bold = "benicons/processor_bold.svg"
        const val processor_light = "benicons/processor_light.svg"
        const val recompile = "benicons/recompile.svg"
        const val refresh = "benicons/refresh.svg"
        const val report_bug = "benicons/report_bug.svg"
        const val return_subroutine = "benicons/return_subroutine.svg"
        const val reverse = "benicons/reverse.svg"
        const val settings = "benicons/settings.svg"
        const val single_exe = "benicons/single_exe.svg"
        const val status_error = "benicons/status_error.svg"
        const val status_fine = "benicons/status_fine.svg"
        const val status_loading = "benicons/status_loading.svg"
        const val step_into = "benicons/step_into.svg"
        const val step_multiple = "benicons/step_multiple.svg"
        const val step_out = "benicons/step_out.svg"
        const val step_over = "benicons/step_over.svg"
        const val tag = "benicons/tag.svg"
        const val split_view = "benicons/split_cells.svg"
        const val combine_view = "benicons/combine_cells.svg"
    }

}